apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: watch-dog
spec:
  selector:
    matchLabels:
      daemon: watch-dog
  template:
    metadata:
      labels:
        daemon: watch-dog
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: watch-dog
          image: redis
