kind: Service
apiVersion: v1
metadata:
  name:  get-configmap-service
spec:
  selector:
    name: get-configmap
  type: ClusterIP
  ports:
  - name:  get-configmap-port
    port:  12345
    targetPort:  9999