kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-sa-bestpractice

subjects:
  - kind: ServiceAccount
    name: system.serviceaccount.default
    namespace: kube-system

roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
