apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mytestrole
  namespace: default
rules:
  - apiGroups: [""]
    verbs:
      - get
      - watch
      - list
    resources:
      - pods

