kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: testrolebinding
  namespace: default
subjects:
  - kind: User
    name: mytestuser
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: mytestrole
  apiGroup: rbac.authorization.k8s.io
